spring:
  application:
    name: kafka-producer
server:
  port: 8090

kafka:
  bootstrap-server: localhost:9092 #,localhost:9094,localhost:9096
  acks: all
  delivery-timeout-ms: 120000
  linger-ms: 0
  request-timeout-ms: 30000
  enable-idempotence: true
  max-in-flight-requests-per-connection: 5
  topic:
    name: product-detail-topic
    partitions: 3
    replicas: 3
    min-insync-replicas: 2